# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai-pt-2',
                'doc_host': 'https://Sina-Haz.github.io',
                'git_url': 'https://github.com/Sina-Haz/fastai-pt-2',
                'lib_path': 'fastai_pt_2'},
  'syms': {'fastai_pt_2.core': {'fastai_pt_2.core.foo': ('core.html#foo', 'fastai_pt_2/core.py')}}}
